public enum Lexer {
    KEYWORD,
    IDENTIFIER,
    LITERAL_INTEGER,
    FLOAT_LITERAL,
    STRING_LITERAL,
    OPERATION_PLUS,
    OPERATION_ASSIGN,
    PUNCTUATION_SEMICOLON,
    WHITE_SPACE,
    COMMENT
}
